cse-config-order: 100

APPLICATION_ID: anta-application

spring:
  application:
    name: anta-scheduler-service-website

service_description:
  version: 0.0.1
  name: ${spring.application.name}

## Spring Boot configurations
server:
  port: 18091

## CSE configurations
servicecomb:
  service:
    registry:
      address: http://localhost:30100
      instance:
        watch: false
  config:
    client:
      serverUri: http://localhost:30113
      refreshMode: 1
  rest:
    address: 0.0.0.0:18091
## static web site will token root
    servlet:
      urlPattern: /api/*
